version: "3.9"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: emp-t3
    environment:
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - db
    command: sh -c "./wait-for-it.sh db:5432 -- npx prisma db push && node server.js"
    networks:
      - emp-net

  db:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    networks:
      - emp-net
    volumes:
      - emp:/var/lib/postgresql
networks:
  emp-net:
volumes:
  emp: